/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.irc;

import org.pircbotx.Configuration;
import org.pircbotx.PircBotX;
import org.pircbotx.UtilSSLSocketFactory;
import org.pircbotx.hooks.ListenerAdapter;
import org.pircbotx.hooks.events.MessageEvent;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;
import software.amazon.awssdk.services.dynamodb.model.AttributeValue;
import software.amazon.awssdk.services.dynamodb.model.PutItemRequest;
import java.time.Instant;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.text.Document;
import java.awt.event.KeyEvent;
import java.io.IOException;
import org.pircbotx.exception.IrcException;
import java.util.List;

/**
 *
 * @author Raony
 */
public class Irc extends javax.swing.JFrame {

    private static final String IRC_SERVER = "irc.libera.chat";
    private static final int IRC_TLS_PORT = 6697;
    private static String NICKNAME = "nickname";
    private static String CHANNEL_TO_JOIN = "#stockmarkets"; // Change this!
    private static final String AWS_REGION = "us-east-1";
    private static final String DYNAMODB_TABLE_NAME = "ChatHistory";
    private static String PASSWORD;
    private String lastResult = "";
    private String base = "";
    private static PircBotX bot;
    private static IrcDao ircDao;
    private boolean acessoinicial;

    /**
     * Creates new form ChatHome
     */
    public Irc() {
        initComponents();
        this.acessoinicial = true;
        if (acessoinicial) {
            txtCommand.setText("Nickname: ");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        txtCommand = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textArea.setEditable(false);
        textArea.setBackground(new java.awt.Color(0, 0, 0));
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        textArea.setForeground(new java.awt.Color(255, 255, 255));
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        txtCommand.setBackground(new java.awt.Color(0, 0, 0));
        txtCommand.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtCommand.setForeground(new java.awt.Color(255, 255, 255));
        txtCommand.setText(">");
        txtCommand.setToolTipText("");
        txtCommand.setCaretColor(new java.awt.Color(255, 255, 255));
        txtCommand.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCommand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCommandKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCommandKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(txtCommand, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCommand, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCommandKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCommandKeyPressed
        String command = this.txtCommand.getText();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (acessoinicial) {
                String nickname = command.substring(11); // Remove '/' and split by space
                NICKNAME = nickname.toLowerCase();
                txtCommand.setText("Password: ");
                String passwordfirst = command.substring(11);
                PASSWORD = passwordfirst;
            }
            if (command.startsWith("/")) {
                handleCommand(command, bot);
            } else {
                // Send as a regular message to the channel
                bot.getUserChannelDao().getChannel(CHANNEL_TO_JOIN).send().message(command);
                atualizaAreaTexto();
            }
            /*String command = this.txtCommand.getText();
            this.adicionarAreaDeTexto(this.txtCommand.getText());

            //eliminando ">" do inicio do comando...
            command = command.substring((this.base.length() + FileSytemSimulator.currentDir.length() + 2), command.length());
            dispararComando(command);

            this.escreverAreaDeTexto();
            this.escreverDiretorio(); */
        }

    }//GEN-LAST:event_txtCommandKeyPressed

    private void txtCommandKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCommandKeyReleased
        /*if (this.txtCommand.getText().length() <= (this.base.length() + FileSytemSimulator.currentDir.length() + 2) || this.txtCommand.getText().length() == 0) {
            this.escreverDiretorio();
        }*/
    }//GEN-LAST:event_txtCommandKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Irc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Irc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Irc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Irc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Thread networkThread = new Thread(new Runnable() {
            public void run() {
                try {
                    System.out.println("Setting up AWS DynamoDB client...");
                    DynamoDbClient ddbClient = DynamoDbClient.builder()
                            .region(Region.of(AWS_REGION))
                            .build();
                    IrcDao ircDao = new IrcDao(ddbClient);
                    System.out.println("AWS clients ready.");

                    // 2. Configure the PircBotX IRC client
                    /*System.out.println("Configuring IRC client...");
        Configuration configuration = new Configuration.Builder()
                .setName(NICKNAME)
                .addServer(IRC_SERVER, IRC_TLS_PORT)
                .setServerPassword(null)
                .setSocketFactory(new UtilSSLSocketFactory().trustAllCertificates(true))
                .addAutoJoinChannel(CHANNEL_TO_JOIN)
                // Pass both the DynamoDbClient and the IrcDao to the listener
                .addListener(new ChatListener(ddbClient, ircDao))
                .buildConfiguration();

        // 3. Start the bot and a separate thread for user input
        System.out.println("Starting IRC bot...");
        PircBotX bot = new PircBotX(configuration);

        // Separate thread to handle messages from the user (console input)
        new Thread(() -> {
            Scanner scanner = new Scanner(System.in);
            System.out.println("You can now type messages. Type 'quit' to exit.");
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                if (line.equalsIgnoreCase("quit")) {
                    System.out.println("Quitting...");
                    bot.stopBot();
                    break;
                }
                if (line.startsWith("/")) {
                    handleCommand(line, bot);
                } else {
                    // Send as a regular message to the channel
                    bot.getUserChannelDao().getChannel(CHANNEL_TO_JOIN).send().message(line);
                }
            }
            scanner.close();
        }).start();*/
                    System.out.println("Configuring IRC client...");
                    Configuration configuration = new Configuration.Builder()
                            .setName(NICKNAME)
                            .addServer(IRC_SERVER, IRC_TLS_PORT)
                            .setServerPassword(null)
                            .setSocketFactory(new UtilSSLSocketFactory().trustAllCertificates())
                            .addAutoJoinChannel(CHANNEL_TO_JOIN)
                            // Pass both the DynamoDbClient and the IrcDao to the listener
                            .addListener(new ChatListener(ddbClient, ircDao, PASSWORD))
                            .buildConfiguration();
                    bot = new PircBotX(configuration);
                    // Start the PircBotX client
                    System.out.println("Starting IRC bot...");
                    try {
                        bot.startBot();
                    } catch (IOException | IrcException e) {
                        System.err.println("Error starting the bot due to an I/O issue: " + e.getMessage());
                        e.printStackTrace(); // Optional: prints the full stack trace for debugging
                    }
                } catch (Exception e) {
                    // Handle exceptions gracefully
                    System.err.println("Network connection failed: " + e.getMessage());
                    e.printStackTrace();
                }
            }
        });
        networkThread.start();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Irc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField txtCommand;
    // End of variables declaration//GEN-END:variables

    private void handleCommand(String line, PircBotX bot) {
        String[] parts = line.substring(1).split(" "); // Remove '/' and split by space
        String command = parts[0].toLowerCase();

        switch (command) {
            case "register":
                if (parts.length >= 3) {
                    String password = parts[1];
                    String email = parts[2];
                    // Send the NickServ registration command
                    bot.sendIRC().message("NickServ", "REGISTER " + password + " " + email);
                    lastResult = "Sent registration request to NickServ. Check your email to verify.";
                } else {
                    lastResult = "Usage: /register <password> <email>";
                }
                break;

            case "identify":
                if (parts.length >= 2) {
                    String password = parts[1];
                    // Send the NickServ identification command
                    bot.sendIRC().message("NickServ", "IDENTIFY " + password);
                    lastResult = "Sent identification request to NickServ.";
                } else {
                    lastResult = "Usage: /identify <password>";
                }
                break;

            case "join":
                if (parts.length >= 2) {
                    String channelToJoin = parts[1];
                    bot.sendIRC().joinChannel(channelToJoin);
                    lastResult = "Attempting to join channel " + channelToJoin;
                } else {
                    lastResult = "Usage: /join <#channel_name>";
                }
                break;

            // You can add more commands here for ChanServ
            case "registerchannel":
                if (parts.length >= 2) {
                    String channelName = parts[1];
                    // Send the ChanServ registration command
                    bot.sendIRC().message("ChanServ", "REGISTER " + channelName);
                    lastResult = "Sent channel registration request to ChanServ.";
                } else {
                    lastResult = "Usage: /registerchannel <#channel_name>";
                }
                break;
            case "getuser":
                if (parts.length >= 2) {
                    String username = parts[1];
                    Map<String, AttributeValue> user = ircDao.getUser(username);
                    if (user != null) {
                        lastResult = "User Data: " + user;
                    }
                } else {
                    lastResult = "Usage: /getuser <username>";
                }
                break;

            case "getchannel":
                if (parts.length >= 2) {
                    String channelName = parts[1];
                    Map<String, AttributeValue> channel = ircDao.getChannel(channelName);
                    if (channel != null) {
                        lastResult = "Channel Data: " + channel;
                    }
                } else {
                    lastResult = "Usage: /getchannel <channel_name>";
                }
                break;

            case "chathistory":
                if (parts.length >= 2) {
                    String channelName = parts[1];
                    List<Map<String, AttributeValue>> history = ircDao.getChatHistoryForChannel(channelName);
                    if (history != null && !history.isEmpty()) {
                        lastResult = "--- Chat History for " + channelName + " ---";
                        for (Map<String, AttributeValue> item : history) {
                            String user = item.get("Username").s();
                            String message = item.get("MessageContent").s();
                            String timestamp = item.get("Timestamp").s();
                            lastResult = lastResult + "/n" + timestamp + " - " + user + " - " + message;
                        }
                        lastResult = lastResult + "/n" + "--- End of History ---";
                    } else {
                        lastResult = "No chat history found for " + channelName;
                    }
                } else {
                    lastResult = "Usage: /chathistory <#channel_name>";
                }
                break;
            case "quit":
                if (parts.length == 1) {
                    System.exit(0);
                } else {
                    lastResult = "Usage: /exit";
                }
                break;
            default:
                lastResult = "Unknown command: " + command;
                break;
        }
    }

    private void escrever() {
        this.txtCommand.setText(this.base);
    }

    private void atualizaAreaTexto() {
        if (!this.lastResult.equals("")) {
            this.textArea.append(this.lastResult);
        }
        this.lastResult = "";
    }

}
